name: Fetch and Save Playlist URL

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Fetch playlist URL
      run: |
        php <<'EOF'
        echo "Fetching playlist URL...";
        $id = "dlxwzh";
        $idn = array(
          "dlxwzh" => "tcb3IB5",
          "dlsh" => "JzcFkF4",
          "dlwt" => "hxT7Fc3",
          "dlys" => "8cuL6wa",
          "dlse" => "q6tZ6Ba",
          "dlgw" => "N4S4uAj",
        );
        $url="https://dlyapp.dltv.cn/apiv4.5/api/m3u8_notoken?channelid=".$idn[$id];
        echo "URL: $url\n";
        $info = file_get_contents($url);
        if ($info === false) {
          echo "Failed to fetch URL\n";
          exit(1);
        }
        preg_match_all('|"address":"(.*?)"|',$info,$playurl);
        if (empty($playurl[1][0])) {
          echo "Failed to extract playlist URL\n";
          exit(1);
        }
        $playlistUrl = str_replace('\/','/',$playurl[1][0]);
        echo "Playlist URL: $playlistUrl\n";
        $result = file_put_contents("大连地方台.txt", $playlistUrl);
        if ($result === false) {
          echo "Failed to write to file\n";
          exit(1);
        }
        echo "File written successfully\n";
        EOF

    - name: 列出目录内容以检查文件是否生成
      run: ls -la

    - name: 查看文件内容以确认生成正确
      run: cat 大连地方台.txt

    - name: 提交并推送更改
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"  # 配置本地 Git 用户邮箱
        git config --local user.name "github-actions[bot]"  # 配置本地 Git 用户名
        git pull origin main  # 先拉取远程更改
        git add 大连地方台.txt  # 确保添加所有生成的 txt 文件
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update playlist with available URLs" && git push)  # 提交更改并推送
